name: GitHub metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Personal metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_music: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          repositories_forks: yes
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C       
          plugin_achievements_secrets: yes   
          plugin_achievements_limit: 0
          plugin_achievements_display: compact   
          plugin_notable: yes
          plugin_tweets_attachments: yes
          plugin_fortune: yes
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about

  github-metrics-detailed-personal:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Personal metrics (detailed)
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.detailed.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_gists: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_pwa: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_languages: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_user: madhavaprmr
          config_timezone: Asia/Kolkata
          plugin_languages_colors: "rainbow"
          plugin_languages_details: bytes-size, percentage
